"use client";

import { useState } from "react";
import Link from "next/link";
import { isVetoed } from "@/lib/genlayer/data-source";

export default function GuardPage() {
  const [governor, setGovernor] = useState(""); const [proposalId, setProposalId] = useState(""); const [answer, setAnswer] = useState<Awaited<ReturnType<typeof isVetoed>>>(); const [loading, setLoading] = useState(false);
  async function check() { setLoading(true); try { setAnswer(await isVetoed(governor.trim(), proposalId.trim())); } finally { setLoading(false); } }
  return <div className="flex max-w-[76ch] flex-col gap-8"><header><p className="ig-label">integration surface</p><h1 className="ig-display mt-3">Ask the guard before execution.</h1><p className="ig-body mt-4">This is the exact question a timelock guard or executor bot asks: whether a particular Governor proposal has a standing Intent Guard veto. A negative result is not proof that it was reviewed.</p></header><form className="grid gap-5 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); void check(); }}><label className="flex flex-col gap-1"><span className="ig-label">governor address</span><input required className="ig-input" value={governor} onChange={(e) => setGovernor(e.target.value)} /></label><label className="flex flex-col gap-1"><span className="ig-label">proposal id</span><input required inputMode="numeric" className="ig-input" value={proposalId} onChange={(e) => setProposalId(e.target.value)} /></label><button className="ig-btn self-start" disabled={loading}>{loading ? "reading…" : "read is_vetoed"}</button></form>{answer ? <section className="ig-recto border border-[var(--rule-strong)] p-5"><p className={`ig-heading ${answer.vetoed ? "ig-rubric" : ""}`}>{answer.vetoed ? "Veto standing" : answer.known ? "No veto standing" : "No record"}</p><p className="ig-body mt-3">{answer.review ? `Review ${answer.review.id} is ${answer.review.status.toLowerCase()}.` : "No review is recorded for this governor and proposal."}</p>{answer.review ? <Link className="ig-calldata-sm mt-3 inline-block underline" href={`/reviews/${answer.review.id}`}>open the review →</Link> : null}</section> : null}<p className="ig-aside">In fixture mode this reads the bundled ledger; in live mode it calls the deployed contract. See the <Link href="/docs" className="underline">documentation</Link> for the structured on-chain response.</p></div>;
}
